### ISSUE TITLE
Create a pull request

### ISSUE THREAD

**Issue by marcelbernic** [bernicuts/unit-converter#2]
In order to merge your new feature in the master branch (the main branch) you need to create a pull request. This is not an issue but more like a task for you. Pull requests are very important in the development process cause they allow for another developer (or yourself) to validate the changes that you want to bring in master (master should ALWAYS be your production-grade application, we don't want ANY errors or ugly code to be pushed in the master branch). Read a little bit about the purpose of pull requests (in general) and create one for your feature branch. Once created, notify @marcelbernic to REVIEW your changes. Once review is completed (and all the comments of the reviewer are fixed) we can merge the branch in master (basically, we can consider that we're moving your code in production).

**Comment by bernicuts** [comment]
ok, I'll try

**Comment by bernicuts** [comment]
cred ca tre sa dai tu add la repo ca nu te pot adauga la pull request

**Comment by marcelbernic** [comment]
All completed
